
#ifndef PROJET_CONFIG_H
#define PROJET_CONFIG_H

//CONFIGURATION DES TEMPS DE COURSE
#define TEMPS_P1 5400       //TEMPS POUR P1 (1H30)
#define TEMPS_P2 5400       //TEMPS POUR P2 (1H30)
#define TEMPS_P3 3600       //TEMPS POUR P3 (1H)
#define TEMPS_Q1 1080       //TEMPS POUR Q1 (18 Minutes)
#define TEMPS_Q2 900        //TEMPS POUR Q2 (15 Minutes)
#define TEMPS_Q3 720        //TEMPS POUR Q3 (12 Minutes)

//CONFIGURATION DE LA COURSE
#define NBRTOTALVOITURE 20  // NOMBRE MAX DE VOITURE
#define FINALTOURS 45       //NOMBRE DE TOUR DE LA FINAL
#define DELAY 1             //DELAI D'AFFICHAGE DES TOURS

//PARAMETRE DE MARGE
#define MAXTIMECOURSE 40000 //TEMPS MAX D'UN TOUR
#define MINTIMECOURSE 25000 //TEMPS MIN D'UN TOUR
#define MINSTANDTIME 5000   //TEMPS MINIMUM D'UN ARRET AU STAND
#define MAXSTANDTIME 10000  //TEMPS MAXIMUM D'UN ARRET AU STAND

//PROBABILITÉ
#define PROBACRACH 250      //PROBABILITÉ DE CRASHE
#define PROBASTAND 35       //PROBABILITÉ D'UN ARRET AU STAND


#endif //PROJET_CONFIG_H
